os:
  - linux
  - osx
language: rust
rust:
  - nightly
sudo: false
branches:
  only:
    - master
install:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh | bash
  - echo $LIBRARY_PATH
  - echo $PKG_CONFIG_PATH
  - echo $PATH
  - export LIBRARY_PATH=$HOME/libsodium-1.0.3/lib:$LIBRARY_PATH && export PKG_CONFIG_PATH=$HOME/libsodium-1.0.3/lib:$PKG_CONFIG_PATH
script:
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/deploy_gh-pages.sh | bash
env:
  global:
    secure: ZQZ1g8GwiCAAbuxCIhos7ZDarFsy83Sl5oDMBQZCavpoT3RAVO+JKw4lK4e9rFI47J8QGubMKbccdVpxc3N5JiV9wtal3s9qefj1FmIYIyKtcpzdD8/AByFCvRln6JhQaRa+sK9PMtaIVJsxtrOhec35THgcp1MOBjIes5UI+NY=
