os:
- linux
- osx
language: rust
rust:
- nightly
sudo: false
branches:
  only:
      - master
      - gh-pages
script:
- cargo build --verbose
- cargo test --verbose
after_success: |
  if  [[ $TRAVIS_BRANCH = master ]] && [[ $TRAVIS_PULL_REQUEST = false ]]; then
    cargo doc &&
    echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
    sudo pip install ghp-import &&
    mkdir docs-stage &&
    COMMIT_MSG=$(git log -1 | tr '[:upper:]' '[:lower:]' | grep "version change to " | tr -d ' ') &&
    git clone https://github.com/${TRAVIS_REPO_SLUG}.git  docs-stage &&
    cd docs-stage &&
    git checkout gh-pages;
    rm -rf .git*;
    # lines 35 - 39 is a patch script for handling old gh-pages structure
    OLD_FILE=$(ls | grep "main.js");
    if [[ $OLD_FILE == main* ]]; then
      rm -rf * &&
      echo "<meta http-equiv=refresh content=0;url=master/`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > index.html;
    fi
    if [[ $COMMIT_MSG == versionchangeto* ]];  then
      VERSION=${COMMIT_MSG##*to} &&
      mkdir -p $VERSION &&
      mkdir -p latest &&
      cp -rf ../target/doc/* $VERSION &&
      cp -rf ../target/doc/* latest &&
      git config --global user.email dev@miadsafe.net &&
      git config --global user.name maidsafe-jenkins &&
      git tag $VERSION -a -m "Version $VERSION" &&
      git push -q https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} --tags;
    fi
    mkdir -p master
    cp -rf ../target/doc/* master &&
    cd .. &&
    ghp-import -n docs-stage &&
    git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages;
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    mkdir kcov-master/build &&
    cd kcov-master/build &&
    cmake .. &&
    make &&
    sudo make install &&
    cd ../.. &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/routing-*;
  fi
env:
  global:
    secure: cOLbJ7YgCw+SIfl0GZ+8dbhqKH12Fo0atTuOcOCUfULXDGx1T9uakFu+yEWUg05U+Tx/e9sKsvpOd7rFT67GB8nAMyNbtWwmpOMY5LUavg2QrF/yIqltNj4+J0MPAt+gde3IXNffnBG4hZNdIG3yjhr+rkfiXCL7S6TLyUzZhkE=
