branches:
  only:
    - bootstrap

platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-$Env:RUST_INSTALL_TRIPLE.exe"
  - cmd: rust-nightly-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /COMPONENTS="rust,gcc,cargo" /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin;
  - rustc --version
  - cargo --version
  - cinst 7zip.commandline -x86
  - ps: if($env:RUST_INSTALL_TRIPLE -eq 'x86_64-pc-windows-gnu') {
         Start-FileDownload "http://libgd.blob.core.windows.net/mingw/mingw-w64-dgn-x86_64-20141001.7z";
         7z x -oC:\ mingw-w64-dgn-x86_64-20141001.7z;        
       }
  - ps: Start-FileDownload 'https://download.libsodium.org/libsodium/releases/libsodium-1.0.2-mingw.tar.gz'
  - 7z e libsodium-1.0.2-mingw.tar.gz && 7z x libsodium-1.0.2-mingw.tar -olibsodium -y
  - if "%RUST_INSTALL_TRIPLE%" == "i686-pc-windows-gnu" mkdir bin\i686-pc-windows-gnu && copy libsodium\libsodium-win32\lib\libsodium.a bin\i686-pc-windows-gnu\ && SET PATH=%PATH%;C:\MinGW\bin;
  - if "%RUST_INSTALL_TRIPLE%" == "x86_64-pc-windows-gnu" mkdir bin\x86_64-pc-windows-gnu && copy libsodium\libsodium-win64\lib\libsodium.a bin\x86_64-pc-windows-gnu\ && SET PATH=%PATH%;C:\mingw64\bin;
  - ps: Start-FileDownload "https://dl.dropboxusercontent.com/s/mqjabz1k67zgst9/libsqlite3.a?dl=0"
  - if "%RUST_INSTALL_TRIPLE%" == "i686-pc-windows-gnu" move .\libsqlite3.a .\bin\i686-pc-windows-gnu\
  - if "%RUST_INSTALL_TRIPLE%" == "x86_64-pc-windows-gnu" move .\libsqlite3.a .\bin\x86_64-pc-windows-gnu\

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
