[package]

name = "routing"
version = "0.1.34"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A specialised storage DHT."
documentation = "http://dirvine.github.io/routing/"
repository = "https://github.com/dirvine/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"


[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "0.0.4"
rand = "*"
message_filter = "*"
lru_time_cache = "0.1.5"
accumulator = "0.0.1"
crust = "0.0.7"
docopt = "*"

[[example]]
name = "routing"
path = "examples/routing.rs"
test = true
bench = false
