[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "A secured storage DHT"
documentation = "http://docs.maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.25.1"

[dependencies]
accumulator = "~0.5.0"
clippy = {version = "~0.0.90", optional = true}
crust = "~0.18.0"
itertools = "~0.4.19"
kademlia_routing_table = "~0.6.0"
log = "~0.3.6"
lru_time_cache = "~0.5.0"
maidsafe_utilities = "~0.9.0"
quick-error = "~1.1.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
rust_sodium = "~0.1.1"
term = "~0.4.4"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.83"
libc = "~0.2.16"

[build-dependencies]
hyper = {version = "~0.9.10", optional = true}

[features]
generate-diagrams = ["hyper"]
use-mock-crust = []

[[example]]
bench = false
name = "key_value_store"
test = false

[[example]]
bench = false
name = "ci_test"
test = false
