[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"
edition = "2018"

[dependencies]
bytes = "~0.4.12"
config_file_handler = "~0.11.0"
crossbeam-channel = "~0.3.9"
fake_clock = "~0.3.0"
fxhash = "~0.2.1"
hex = "~0.2.0"
hex_fmt = "~0.1.0"
itertools = "~0.6.1"
log = "~0.3.8"
lru_time_cache = "~0.8.1"
maidsafe_utilities = "~0.18.0"
num-bigint = "~0.1.40"
parsec = { git = "https://github.com/maidsafe/parsec", rev = "b96e6016" }
# quic-p2p = "~0.2.0"
quic-p2p = { git = "https://github.com/maidsafe/quic-p2p" }
quick-error = "~1.2.0"
rand = "~0.3.16"
# rand in the version used by threshold_crypto and ed25519_dalek crates, for compatibility
rand_crypto = { package = "rand", version = "~0.6.5" }
resource_proof = "~0.8.0"
serde = "~1.0.25"
serde_derive = "~1.0.25"
term = "~0.4.6"
tiny-keccak = "~1.5.0"
ed25519_dalek = { package = "tmp-ed25519", version = "1.0.0-pre.2", features = ["serde"] }
threshold_crypto = "~0.3.2"
unwrap = "~1.2.1"

[dev-dependencies]
docopt = "~0.8.1"
libc = "~0.2.29"
serde_json = "~1.0.8"

[features]
mock_base = ["lru_time_cache/fake_clock", "parsec/mock", "parsec/malice-detection"]
mock_crypto = ["mock_base"]
mock_parsec = ["mock_base"]
mock_serialise = ["mock_base"]
mock = ["mock_crypto", "mock_parsec", "mock_serialise"]
