[package]

name = "Routing"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/routing/routing"
repository = "https://github.com/dirvine/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
#rand = "0.1.3"
#rust-crypto = "*"

[dependencies.utp]
git = "https://github.com/dirvine/rust-utp"

[dependencies.sodiumoxide]
git = "https://github.com/dnaq/sodiumoxide"

[dependencies.msgpack]
git = "https://github.com/mneumann/rust-msgpack"
