[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.6.1"

[dependencies]
accumulator = "~0.1.3"
cbor = "~0.3.16"
crust = "~0.8.0"
ip = "~1.0.0"
itertools = "~0.4.5"
kademlia_routing_table = "~0.0.4"
log = "~0.3.4"
lru_time_cache = "~0.2.5"
maidsafe_utilities = "~0.1.5"
message_filter = "~0.2.0"
rustc-serialize = "~0.3.16"
sodiumoxide = "~0.0.9"
time = "~0.1.34"
xor_name = "~0.0.1"

[dev-dependencies]
bit-vec = "~0.4.2"
docopt = "~0.6.78"
env_logger = "~0.3.2"
rand = "~0.3.12"

[[example]]
bench = false
name = "key_value_store"
test = true

[[example]]
bench = false
name = "ci_test"
test = true
