[package]

name = "maidsafe_vault"
version = "0.0.3"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/maidsafe_vault/"
repository = "https://github.com/dirvine/maidsafe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide = "*"
rand = "*"
lru_time_cache = "0.1.4"
routing = "0.1.2"

[dependencies.maidsafe_types]
git = "https://github.com/dirvine/maidsafe_types.git"
