[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.11.1"

[dependencies]
accumulator = "~0.2.0"
clippy = {version = "~0.0.46", optional = true}
crust = "~0.9.0"
itertools = "~0.4.10"
kademlia_routing_table = "~0.4.0"
log = "~0.3.5"
lru_time_cache = "~0.2.7"
maidsafe_utilities = "~0.4.0"
message_filter = "~0.3.1"
rand = "~0.3.14"
rustc-serialize = "~0.3.18"
sodiumoxide = "~0.0.9"
time = "~0.1.34"
xor_name = "~0.1.0"

[dev-dependencies]
docopt = "~0.6.78"
libc = "~0.2.7"

[features]
use-mock-crust = []

[[example]]
bench = false
test = false
name = "key_value_store"

[[example]]
bench = false
test = false
name = "ci_test"
