[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "A secured storage DHT"
documentation = "http://docs.maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.23.2"

[dependencies]
accumulator = "~0.4.0"
clippy = {version = "~0.0.77", optional = true}
crust = "~0.16.0"
itertools = "~0.4.16"
kademlia_routing_table = "~0.6.0"
log = "~0.3.6"
lru_time_cache = "~0.4.0"
maidsafe_utilities = "~0.8.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "=0.0.10"
sodiumoxide_extras = {version = "~0.1.0", optional = true}
term = "~0.4.4"
unwrap = "~1.1.0"

[dev-dependencies]
docopt = "~0.6.81"
libc = "~0.2.12"
sodiumoxide_extras = "~0.1.0"

[build-dependencies]
hyper = {version = "~0.9.9", optional = true}

[features]
generate-diagrams = ["hyper"]
use-mock-crust = ["sodiumoxide_extras"]

[[example]]
bench = false
name = "key_value_store"
test = false

[[example]]
bench = false
name = "ci_test"
test = false
