[package]

name = "routing"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/routing/"
repository = "https://github.com/dirvine/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
sodiumoxide= "*"

[dependencies.bchannel]
git="https://github.com/dirvine/bchannel"

[dependencies.lru-cache]
git="https://github.com/contain-rs/lru-cache.git"

[dependencies.sqlite3]
git="https://github.com/linuxfood/rustsqlite.git"

[dependencies.maidsafe_types]
git = "https://github.com/dirvine/maidsafe_types"
