[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"
edition = "2018"

[dependencies]
bytes = "~0.4.12"
config_file_handler = "~0.11.0"
crossbeam-channel = "~0.3.9"
ctrlc = { version = "~3", optional = true, features = ["termination"] }
fake_clock = "~0.3.0"
fxhash = "~0.2.1"
hex = "~0.2.0"
hex_fmt = "~0.1.0"
itertools = "~0.6.1"
lazy_static = { version = "~1", optional = true }
log = "~0.3.8"
lru_time_cache = "~0.8.1"
maidsafe_utilities = "~0.18.0"
num-bigint = "~0.1.40"
parsec = { git = "https://github.com/maidsafe/parsec", rev = "818676c" }
# quic-p2p = "~0.2.0"
quic-p2p = { git = "https://github.com/maidsafe/quic-p2p" }
# rand in the version used by threshold_crypto and ed25519_dalek crates, for compatibility
rand_crypto = { package = "rand", version = "~0.6.5" }
resource_proof = "~0.8.0"
serde = { version = "~1.0.25", features = ["rc"] }
serde_derive = "~1.0.25"
serde_json = "~1.0.8"
structopt = "~0.2.18"
term = "~0.4.6"
tiny-keccak = "~1.5.0"
ed25519_dalek = { package = "tmp-ed25519", version = "1.0.0-pre.2", features = ["serde"] }
threshold_crypto = "~0.3.2"
unwrap = "~1.2.1"
derive_more = "0.99.2"
err-derive = "0.2.1"
rand = "0.7.2"
rand_core = "0.5.1"
rand_xorshift = "0.2.0"

[dev-dependencies]
docopt = "~0.8.1"
libc = "~0.2.29"

[features]
mock_base = ["lru_time_cache/fake_clock", "parsec/mock", "parsec/malice-detection", "ctrlc", "lazy_static"]
mock_crypto = ["mock_base", "threshold_crypto/use-insecure-test-only-mock-crypto"]
mock_parsec = ["mock_base"]
mock_serialise = ["mock_base"]
mock = ["mock_crypto", "mock_parsec", "mock_serialise"]
