[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"
edition = "2018"

[dependencies]
bytes = "~0.4.12"
config_file_handler = "~0.11.0"
crossbeam-channel = "~0.3.8"
fake_clock = "~0.3.0"
fxhash = { version = "~0.2.1", optional = true }
hex = "~0.2.0"
hex_fmt = "~0.1.0"
itertools = "~0.6.1"
lazy_static = "~1.2.0"
log = "~0.3.8"
lru_time_cache = "~0.8.1"
maidsafe_utilities = "~0.18.0"
num-bigint = "~0.1.40"
parsec = { git = "https://github.com/maidsafe/parsec", rev = "226e9e25" }
quic-p2p = "~0.2.0"
quick-error = "~1.2.0"
rand = "~0.3.16"
resource_proof = "~0.6.0"
safe_crypto = "~0.7.0"
serde = "~1.0.25"
serde_derive = "~1.0.25"
term = "~0.4.6"
unwrap = "~1.2.1"
tiny-keccak = "1.4.4"

[dev-dependencies]
docopt = "~0.8.1"
libc = "~0.2.29"
serde_json = "~1.0.8"

[features]
mock_base = ["lru_time_cache/fake_clock", "safe_crypto/mock", "parsec/mock", "parsec/malice-detection", "fxhash"]
mock_parsec = ["mock_base"]
mock_serialise = ["mock_base"]
mock = ["mock_parsec", "mock_serialise"]

[[example]]
bench = false
name = "key_value_store"

[[example]]
bench = false
name = "ci_test"
