[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.net/routing/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.18.4"
build = "build.rs"

[dependencies]
accumulator = "~0.3.0"
clippy = {version = "~0.0.64", optional = true}
crust = "~0.12.0"
itertools = "~0.4.13"
kademlia_routing_table = "~0.5.1"
log = "~0.3.6"
lru_time_cache = "~0.3.1"
maidsafe_utilities = "~0.5.4"
message_filter = "~0.5.0"
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
sodiumoxide = "~0.0.10"
term = "~0.4.4"
xor_name = "~0.1.0"

[dev-dependencies]
docopt = "~0.6.80"
libc = "~0.2.10"

[build-dependencies]
hyper = "0.8.0"

[features]
use-mock-crust = []
generate-diagrams = []

[[example]]
bench = false
name = "key_value_store"
test = false

[[example]]
bench = false
name = "ci_test"
test = false
