[package]
name = "routing"
version = "0.3.12"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "http://maidsafe.net/routing/latest"
repository = "https://github.com/maidsafe/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "*"
time = "*"
rand = "*"
message_filter = "0.1.*"
lru_time_cache = "0.2.*"
accumulator = "0.1.*"
docopt = "*"
itertools = "*"
log = "*"
env_logger = "*"
sodiumoxide = "*"
crust = "0.2.*"

[dev-dependencies]
bit-vec = "*"

[[example]]
name = "simple_key_value_store"
path = "examples/simple_key_value_store.rs"
test = true
bench = false

[[example]]
name = "key_value_store"
path = "examples/key_value_store.rs"
test = true
bench = false

[[bin]]
name = "node"
path = "tests/node.rs"
test = false
bench = false

[[bin]]
name = "churn_node"
path = "tests/churn_node.rs"
test = false
bench = false
