[package]
name = "safe_vault"
version = "0.1.6"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://maidsafe.net/safe_vault/latest"
repository = "https://github.com/maidsafe/safe_vault"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
# ---- Non-MaidSafe -----
cbor = "*"
log = "*"
env_logger = "*"
rand = "*"
rustc-serialize = "*"
sodiumoxide = "*"
tempdir = "*"
time = "*"

# ---- MaidSafe ------
lru_time_cache = "0.2.*"
routing = "0.3.*"

[features]
use-mock-routing = []
