[package]

name = "Routing"
version = "0.0.1"
authors = ["David Irvine <david.irvine@maidsafe.net>"]
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://dirvine.github.io/routing/"
repository = "https://github.com/dirvine/routing"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://www.maidsafe.net"

[dependencies]
rustc-serialize = "*"
cbor = "0.2.2"
bchannel = "*"
lru-cache = "0.0.1"
time = "0.1.20"

[dependencies.utp]
git = "https://github.com/meqif/rust-utp"

[dependencies.sodiumoxide]
git = "https://github.com/krishnaindia/sodiumoxide"

