[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
description = "This is Pre alpha, and not useful, no code worth looking at."
documentation = "http://docs.maidsafe.net/safe_vault/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_vault"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_vault"
version = "0.9.0"

[dependencies]
accumulator = "~0.4.0"
clippy = {version = "~0.0.76", optional = true}
config_file_handler = "~0.3.1"
docopt = "~0.6.80"
itertools = "~0.4.16"
lru_time_cache = "~0.4.0"
kademlia_routing_table = "~0.6.0"
log = "~0.3.6"
maidsafe_utilities = "~0.8.0"
quick-error = "~1.1.0"
rand = "~0.3.14"
routing = "~0.23.0"
rustc-serialize = "~0.3.19"
safe_network_common = "~0.4.0"
sodiumoxide = "~0.0.10"

[build-dependencies]
hyper = {version = "~0.9.6", optional = true}

[dev-dependencies]
tempdir = "~0.3.4"

[features]
generate-diagrams = ["hyper"]
use-mock-crust = ["routing/use-mock-crust"]

[[test]]
name = "tests"

[[bin]]
name = "safe_vault"
doc = false
